package com.singht.springboot.jpa;

import java.util.List;

//import org.springframework.stereotype.Repository;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
//import com.singht.springboot.jpa.User;


// Specify the java table mapped class and the the autogenerated field.
@Repository
public interface UserRepository extends CrudRepository<User, Long>{

	List<User>findByRole(String role);
}
