package com.singht.springboot.jpa;

import java.util.List;

import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
//import com.singht.springboot.jpa.User;


// Specify the java table mapped class and the the autogenerated field.
@RepositoryRestResource(path="users", collectionResourceRel="users")
public interface UserRestRepository extends PagingAndSortingRepository<User, Long>{

	List<User>findByRole(@Param("role") String role);
}
